# use Travis container build infrastructure
sudo: false
language:
  - python
python:
  - '2.7'
install:
  - gem install sass
  - gem install compass
  - pip install coveralls
  - pip install mandrill
  - pip install pyramid_redis_sessions
  - make
script:
  - make test
  - make cover
  - hypothesis-buildext conf/testext.ini chrome --base http://localhost
  - hypothesis-buildext conf/testext.ini firefox --base http://localhost
  - "hypothesis-buildext conf/production.ini chrome
    --base https://hypothes.is
    --assets chrome-extension://notarealkey/public"
  - "hypothesis-buildext conf/production.ini firefox
    --base https://hypothes.is
    --assets resource://notarealkey/hypothesis/data"
after_success:
  - coveralls
notifications:
  irc:
    channels:
       "chat.freenode.net#hypothes.is"
    on_success: "change"
    on_failure: "always"
